Issue #10 risolta
ittagnelli/ats pull request #12
Opened 2021-09-28 15:51 UTC by Dario-Ruggieri

Abbiamo nascosto la sezione "Testimonial" e il relativo bottone. 
Buona giornata.

Il gruppo DEV

2021-09-28 16:50 UTC, Dario-Ruggieri commented
Professore ci siamo accorti che il push ha preso anche le modifiche del branch riguardante l'invio delle email.
Con la pull request della issue #4 si sistemerà tutto, per ora è da considerare solo il cambiamento riguardante la sezione Testimonial.
Ci scusiamo per l'inconveniente.
Il gruppo DEV

2021-09-28 19:39 UTC, mancusoa74 requested changes
Ci sono varie cose che non capisco

1- la funzione di invio email non è pertinente a questa issue e PR --> rimuovere
2- non vedo il motivo dell'aggiunta di una nuova classe testimonial-section-padding e della rimozione delle classi testimonial e section-padding. si suggerisce solo di modificare la classe testimonial o di aggiungere una nuova classe hide/nascodi/etcc senza rimuovere le classi originali

per tali motivi questa pull request non può essere accettata così.
fare le modifiche richieste in modo che posso accettare la pull requeste e fare il merge

grazie

2021-10-02 09:04 UTC, Dario-Ruggieri commented
Adesso dovrebbe essere tutto apposto.
Devo aver fatto qualche casino con i branch.
Aspettiamo approvazione.

2021-10-03 16:30 UTC, mancusoa74 approved these changes

2021-10-03 16:31 UTC, mancusoa74 commented
ok c'erano dei conflitti che ho risolto io

2021-10-03 16:31 UTC, merged