Fatto le modifiche richieste
ittagnelli/ats pull request #59
Opened 2023-10-10 13:35 UTC by Licciardino-Matteo

Ho tolto le foto dei vecchi fondatori e ho messo le foto degli attuali partecipanti

2023-10-10 18:13 UTC, profmancusoa requested changes
com'era

![image](https://github.com/ittagnelli/ats/assets/111191978/6d077e54-77fc-4a10-8025-1fd7cbebe2a6)


com'e'

![image](https://github.com/ittagnelli/ats/assets/111191978/65b54f2e-31c1-429e-a317-15299e7ca551)

2023-10-10 19:20 UTC, Licciardino-Matteo commented
Ho aggiunto la foto di Widsom, inoltre ho modificato la foto di Mariotti

2023-10-11 18:55 UTC, Licciardino-Matteo commented
Ho messo lo sfondo bianco alle foto, e altre modifiche che ho fatto

2023-10-12 07:26 UTC, profmancusoa requested changes
![image](https://github.com/ittagnelli/ats/assets/111191978/77775ddf-c4e9-4ab7-8cb5-e59e5968d20d)

direi che la qualità non va bene

2023-10-12 16:41 UTC, Licciardino-Matteo commented
Ho cercato di migliorare la qualità della foto, inoltre messo altre foto di me, di master e di Gioele

2023-10-12 19:57 UTC, profmancusoa approved these changes
ok va bene così grazie

2023-10-12 20:04 UTC, Licciardino-Matteo commented
Ho rimosso lo sfondo di qualche foto del team di ATS.

2023-10-12 20:15 UTC, profmancusoa commented
questa PR non può essere mergata.
devi aggiornare il tuo branch con il main di ATS, poi risolvrere i conflitti e poi aggiornare queata PR

prima di fare una PR è sempre necessario fare un merge dal main che nel frattempo è cambiato

2023-10-13 08:24 UTC, closed without merging